import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { db, auth, handleFirestoreError, OperationType } from '../../lib/firebase';
import { collection, query, where, getDocs, addDoc } from 'firebase/firestore';
import { TRANSLATIONS } from '../../constants';
import { Language, Ledger, UserProfile } from '../../types';
import { ChevronLeft, FileText, Send, CheckCircle, Download, Share2, Printer } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { cn } from '../../lib/utils';
import confetti from 'canvas-confetti';

export default function ChallanGenerator({ setView, lang, profile, darkMode }: { setView: (v: any) => void, lang: Language, profile: UserProfile | null, darkMode?: boolean }) {
  const t = TRANSLATIONS[lang];
  const [ledgers, setLedgers] = useState<Ledger[]>([]);
  const [buyerId, setBuyerId] = useState('');
  const [truckNumber, setTruckNumber] = useState('');
  const [driverName, setDriverName] = useState('');
  const [weight, setWeight] = useState('');
  const [generating, setGenerating] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);

  useEffect(() => {
    const fetchLedgers = async () => {
      const uid = auth.currentUser?.uid || profile?.uid;
      if (!uid || uid === 'guest-preview') return;
      const q = query(collection(db, 'ledgers'), where('ownerId', '==', uid));
      const snap = await getDocs(q);
      setLedgers(snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as Ledger)));
    };
    fetchLedgers();
  }, []);

  const generatePDF = () => {
    setGenerating(true);
    const selectedBuyer = ledgers.find(l => l.id === buyerId);
    
    // STRICTLY DETERMINISTIC PDF GENERATION
    const doc = new jsPDF();
    const challanNo = `C-${Date.now().toString().slice(-6)}`;
    
    // Template
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("DELIVERY CHALLAN", 105, 20, { align: "center" });
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Challan No: ${challanNo}`, 20, 40);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 45);
    
    doc.setLineWidth(0.5);
    doc.line(20, 50, 190, 50);
    
    doc.setFont("helvetica", "bold");
    doc.text("CONSIGNEE / BUYER:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(selectedBuyer?.buyerName || "N/A", 20, 65);
    doc.text(selectedBuyer?.buyerPhone || "N/A", 20, 70);
    
    doc.setFont("helvetica", "bold");
    doc.text("LOGISTICS DETAILS:", 20, 85);
    doc.setFont("helvetica", "normal");
    doc.text(`Truck Number: ${truckNumber}`, 20, 90);
    doc.text(`Driver Name: ${driverName}`, 20, 95);
    doc.text(`Load Weight: ${weight} KG`, 20, 100);
    
    doc.line(20, 110, 190, 110);
    
    doc.setFontSize(8);
    doc.text("This is an electronically generated document by Keystone SME.", 105, 280, { align: "center" });

    // Trigger download
    doc.save(`Challan-${challanNo}.pdf`);
    
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    setPdfUrl(url);
    setGenerating(false);
    
    // Log to DB
    const logChallan = async () => {
       const uid = auth.currentUser?.uid || profile?.uid;
       if (!uid) return;
       try {
         await addDoc(collection(db, 'challans'), {
            userId: uid,
            buyerId,
            buyerName: selectedBuyer?.buyerName,
            truckNumber,
            driverName,
            itemWeight: Number(weight),
            challanNumber: challanNo,
            timestamp: new Date().toISOString()
         });
       } catch (error) {
         handleFirestoreError(error, OperationType.WRITE, 'challans');
       }
    };
    logChallan();
    
    confetti({ particleCount: 50, spread: 60 });
  };

  const shareToWhatsApp = () => {
    const selectedBuyer = ledgers.find(l => l.id === buyerId);
    const text = `Challan Generated for ${selectedBuyer?.buyerName}.\nTruck: ${truckNumber}\nWeight: ${weight}kg\nGenerated by Keystone SME.`;
    window.open(`https://wa.me/${selectedBuyer?.buyerPhone}?text=${encodeURIComponent(text)}`);
  };

  return (
    <div className={cn("flex flex-col h-full transition-colors duration-300", 
      darkMode ? "bg-zinc-950" : "bg-[#1D1D1F]")}>
      <div className={cn("p-6 flex items-center gap-4 transition-colors", 
        darkMode ? "text-white" : "text-white")}>
         <button onClick={() => setView('dashboard')} className={cn("w-10 h-10 rounded-full flex items-center justify-center transition-colors",
           darkMode ? "bg-white/5" : "bg-white/10")}>
           <ChevronLeft size={24} />
         </button>
         <h2 className="text-xl font-bold italic tracking-tight">{t.createChallan}</h2>
      </div>

      <div className={cn("flex-1 rounded-t-[40px] p-8 shadow-2xl space-y-8 overflow-y-auto transition-colors",
        darkMode ? "bg-zinc-900 shadow-none border-t border-white/5" : "bg-white")}>
         {!pdfUrl ? (
           <>
              <div className="space-y-6">
                <div className="space-y-2">
                  <p className={cn("text-xs font-bold uppercase tracking-widest transition-colors",
                    darkMode ? "text-zinc-500" : "text-gray-400")}>Select Buyer</p>
                  <select 
                    className={cn("w-full text-xl font-bold bg-transparent border-b-2 outline-none pb-2 appearance-none transition-all",
                      darkMode ? "border-white/10 text-white focus:border-purple-500" : "border-gray-100 text-zinc-900 focus:border-purple-500")}
                    value={buyerId}
                    onChange={e => setBuyerId(e.target.value)}
                  >
                    <option value="" className={darkMode ? "bg-zinc-900" : ""}>Choose Buyer...</option>
                    {ledgers.map(l => (
                      <option key={l.id} value={l.id} className={darkMode ? "bg-zinc-900" : ""}>{l.buyerName}</option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <p className={cn("text-xs font-bold uppercase tracking-widest transition-colors",
                    darkMode ? "text-zinc-500" : "text-gray-400")}>Truck Number</p>
                  <input className={cn("w-full text-xl font-bold bg-transparent border-b-2 outline-none pb-2 transition-all",
                    darkMode ? "border-white/10 text-white focus:border-purple-500 placeholder:text-zinc-700" : "border-gray-100 text-zinc-900 focus:border-purple-500 placeholder:text-gray-300")} 
                         placeholder="e.g. Dhaka-Metro-T-1234"
                         value={truckNumber} onChange={e => setTruckNumber(e.target.value)} />
                </div>

                <div className="space-y-2">
                  <p className={cn("text-xs font-bold uppercase tracking-widest transition-colors",
                    darkMode ? "text-zinc-500" : "text-gray-400")}>Driver Name</p>
                  <input className={cn("w-full text-xl font-bold bg-transparent border-b-2 outline-none pb-2 transition-all",
                    darkMode ? "border-white/10 text-white focus:border-purple-500" : "border-gray-100 text-zinc-900 focus:border-purple-500")} 
                         value={driverName} onChange={e => setDriverName(e.target.value)} />
                </div>

                <div className="space-y-2">
                  <p className={cn("text-xs font-bold uppercase tracking-widest transition-colors",
                    darkMode ? "text-zinc-500" : "text-gray-400")}>Load Weight (KG)</p>
                  <input type="number" className={cn("w-full text-xl font-bold bg-transparent border-b-2 outline-none pb-2 transition-all",
                    darkMode ? "border-white/10 text-white focus:border-purple-500" : "border-gray-100 text-zinc-900 focus:border-purple-500")} 
                         value={weight} onChange={e => setWeight(e.target.value)} />
                </div>
              </div>

              <button 
                disabled={!buyerId || !truckNumber || !weight}
                onClick={generatePDF}
                className={cn("w-full py-5 rounded-3xl font-bold text-lg flex items-center justify-center gap-3 disabled:opacity-50 mt-12 transition-all",
                  darkMode ? "bg-purple-600 text-white shadow-xl shadow-purple-900/20" : "bg-[#7C3AED] text-white shadow-lg shadow-purple-100") }
              >
                {generating ? <RefreshCw className="animate-spin" /> : <>{t.generatePdf} <FileText /></>}
              </button>
           </>
         ) : (
           <motion.div 
             initial={{ scale: 0.9, opacity: 0 }}
             animate={{ scale: 1, opacity: 1 }}
             className="text-center space-y-8 py-4"
           >
              <div className={cn("w-24 h-24 rounded-full flex items-center justify-center mx-auto transition-colors",
                darkMode ? "bg-green-500/10 text-green-400" : "bg-green-50 text-green-500")}>
                 <CheckCircle size={56} />
              </div>
              <h3 className={cn("text-2xl font-black italic transition-colors", 
                darkMode ? "text-white" : "text-zinc-900")}>Challan Ready</h3>
              
              <div className={cn("aspect-[1/1.414] rounded-2xl overflow-hidden border shadow-inner p-4 transition-colors",
                darkMode ? "bg-zinc-800 border-white/5" : "bg-gray-100 border-gray-100")}>
                 <iframe src={pdfUrl} className="w-full h-full rounded-lg" title="PDF Preview" />
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <button 
                   onClick={() => window.open(pdfUrl)}
                   className={cn("py-4 rounded-2xl font-bold flex items-center justify-center gap-2 transition-all",
                     darkMode ? "bg-white/5 text-white" : "bg-gray-100 text-gray-700 hover:bg-gray-200") }
                 >
                   <Download size={20} /> View
                 </button>
                 <button 
                   onClick={shareToWhatsApp}
                   className="bg-[#25D366] text-white py-4 rounded-2xl font-bold flex items-center justify-center gap-2 active:scale-95 transition-transform"
                 >
                   <Share2 size={20} /> WhatsApp
                 </button>
              </div>

              <button 
                onClick={() => setPdfUrl(null)}
                className={cn("font-bold uppercase tracking-widest text-xs transition-colors",
                  darkMode ? "text-zinc-500 hover:text-white" : "text-gray-400 hover:text-gray-600")}
              >
                 Create Another
              </button>
           </motion.div>
         )}
      </div>
    </div>
  );
}

function RefreshCw(props: any) {
  return (
    <svg 
      {...props}
      xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" 
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M3 21v-5h5" />
    </svg>
  )
}
