export const APP_NAME = "Keystone SME";

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome back",
    chooseLanguage: "Choose Language",
    phoneLogin: "Phone Login",
    enterOtp: "Enter OTP",
    next: "Next",
    scanNid: "Align your Smart NID",
    farmSetup: "Farm/Business Setup",
    businessName: "Business Name",
    category: "Category",
    location: "Location",
    trustScoreBtn: "Tap for Trust Score & Daily Sales",
    newSale: "New Sale",
    scanReceipt: "Scan Receipt",
    createChallan: "Create Challan",
    marketRates: "Market Rates",
    recentActivity: "Recent Activity Feed",
    totalDue: "Total Due (Pabo)",
    totalPaid: "Total Paid (Diyeche)",
    sendSms: "Send SMS",
    generatePdf: "Generate PDF",
    confirm: "Confirm",
    breakEven: "Break-even Gauge",
    baki: "Baki",
    cash: "Cash",
    poultry: "Poultry",
    agro: "Agro",
    dairy: "Dairy",
    other: "Other"
  },
  bn: {
    welcome: "স্বাগতম",
    chooseLanguage: "ভাষা নির্বাচন করুন",
    phoneLogin: "ফোন লগইন",
    enterOtp: "ওটিপি লিখুন",
    next: "পরবর্তী",
    scanNid: "আপনার স্মার্ট এনআইডি কার্ডটি ফ্রেমের ভেতরে রাখুন",
    farmSetup: "খামারের বিবরণ",
    businessName: "প্রতিষ্ঠানের নাম",
    category: "বিভাগ",
    location: "অবস্থান",
    trustScoreBtn: "ট্রাস্ট স্কোর এবং দৈনিক বিক্রয় দেখুন",
    newSale: "নতুন বিক্রয়",
    scanReceipt: "রসিদ স্ক্যান করুন",
    createChallan: "চালান তৈরি করুন",
    marketRates: "বাজার দর",
    recentActivity: "সাম্প্রতিক কার্যক্রম",
    totalDue: "মোট পাওনা (পাবো)",
    totalPaid: "মোট পরিশোধ (দিয়েছে)",
    sendSms: "এসএমএস পাঠান",
    generatePdf: "পিডিএফ তৈরি করুন",
    confirm: "নিশ্চিত করুন",
    breakEven: "ব্রেক-ইভেন গেজ",
    baki: "বাকি",
    cash: "নগদ",
    poultry: "পোল্ট্রি",
    agro: "কৃষি",
    dairy: "ডেইরি",
    other: "অন্যান্য"
  }
};
